# Generated by Django 4.2.1 on 2023-05-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='Vaccination',
            new_name='vaccinations',
        ),
    ]
